### ISSUE TITLE
SCORES

### ISSUE THREAD

**Issue by caslive** [rubynor/bigfive-web#10]
I have seen that now it appears the score, but I have already done the tests to people. Could you please say to me the scores here? Like: 0-40 low, 41-90 average, 91-120 high. And above of all, there is not a legend in the results, to know that. Thank you very much in advance.

**Comment by lucasrato** [comment]
Yes, I'd like to know more about this as well. I now it isn't simple as 0-40 low, because I saw a result with a 16 high in one of the traits, but I'd love to see a table where I could convert these values into percentiles
