### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by tordbb** [rubynor/bigfive-web#11]
After filling out the last question, I am shown the button "See Results". When I press it, a notification pops up saying "Network Error". This repeats even though I can open another tab and go to a website without any problems. Possibly this problem was caused by my wifi being down at some earlier instant - my wifi goes down now and then. Me and a few colleagues all did the bigfive-test at the same time, and one of them had exactly the same problem as I did. 
After a while, I tried right clicking and "reload frame", but then I was sent to the very start page and asked to do the entire test all over again (lost my motivation to do that).

**Comment by martgra** [comment]
Getting the same error. Opening "console" in Chrome and getting the following message:

Access to XMLHttpRequest at 'https://b5.rubynor.xyz/api/save' from origin 'https://bigfive-test.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by maccyber** [comment]
Oh shit, sorry guys.

Could not repoduce, but the saving URL should be https://bigfive-test.com/api/save.
Will a fix.

Thanks for reporting, sorry again for the trouble

**Comment by maccyber** [comment]
Deployed new version that should post til the right API-url.

May also be something with the CORS:
https://github.com/rubynor/bigfive-web/blob/master/now.json#L40-L54

https://github.com/rubynor/bigfive-web/blob/master/api/save.js#L6-L9

But I can not reproduce the error.

**Comment by maccyber** [comment]
I have not received any messages about this error after the lastest change.

So I'm closing this issue.
