### ISSUE TITLE
There are some issues in the french texts, where can i fix them?

### ISSUE THREAD

**Issue by arnaudlevy** [rubynor/bigfive-web#12]

**Comment by maccyber** [comment]
Hi @arnaudlevy.

Thanks for showing interest in bigfive-web.

There are two repos:

**Result text**
https://github.com/Alheimsins/b5-result-text/tree/master/lib/data/fr

**Question set**
https://github.com/Alheimsins/b5-johnson-120-ipip-neo-pi-r/tree/master/data/fr
