### ISSUE TITLE
Upgrade dependencies for Node 18

### ISSUE THREAD

**Issue by Zachary-Love** [rubynor/bigfive-web#126]
Vercel has deprecated Node 14, and Node 16 is up next. It would be best to bump dependencies so that we can use Node 18. I can open a PR for this if the idea is approved.

Goals:
- Bump dependencies in `package.json`
- Bump version in dockerfile & docker-compose

**Comment by maccyber** [comment]
That would be awesome @Zachary-Love :partying_face:
