### ISSUE TITLE
Issue with Bahasa Indonesia translation

### ISSUE THREAD

**Issue by isaid-hi** [rubynor/bigfive-web#13]
In the test, indifferent translated as "acuh".
Acuh, in Bahasa Indonesia meaning heed or care. Indonesian people themselves very often misinterpret acuh as indifferent.
This issue can lead to false internal consistency due to misinterpreting item rather than its true meaning

**Comment by maccyber** [comment]
Hi @isaid-hi, thanks for the notice.

Do you have a suggestion for a word replacement?

https://github.com/Alheimsins/b5-johnson-120-ipip-neo-pi-r/blob/main/data/id/questions.json#L515

**Comment by isaid-hi** [comment]
Firstly, thanks for your reply.
Actually, I suggest to translate "indifferent" as "acuh tak acuh" or "masa bodoh" (not "acuh" as on the site) by considering those definition similarity:

Indifferent : 1. Having no particular interest or sympathy; unconcerned; 2. neither good nor bad; mediocre; 3. neutral in respect of some specified physical property.

Acuh: Care; heed.

Acuh tak acuh: (there is no official translation for this term from the government, but i am pretty sure that the best english translation is "indifferent", since "acuh" means "care/heed" and "tak" means "not")

Masa bodoh: 1. affective words to express displeasure; up to you; whatever you like: this way you don't want to, that way you don't want to. 2. doesn't matter; not paying attention at all; (acuh tak acuh); does not care about anything; don't think about other people's cases 

P.S.: I am not expert in Bahasa Indonesia, yet i hope some expert can see this to help with correct translation.
Btw, thank you very much for this great job!
