### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by DagonChernovski** [rubynor/bigfive-web#131]
I just did the Russian results section and made a pull request [here](https://github.com/Alheimsins/b5-result-text/pull/210), and there were other pulls since 2023. Not sure where else it should done, but would you approve it or update the translations in any way it would work?

UPD: I figured out the folder and that they need to be translated to TypeScript.

**Comment by maccyber** [comment]
@DagonChernovski: That is awesome!!! Thanks. Will publish it now.
We are in the middle of a rewrite, so things are a bit messy

**Comment by maccyber** [comment]
a million thanks @DagonChernovski

Should be live at https://bigfive-test.com/ru/result/6626d88add128a9f799eeec4?lang=ru
