### ISSUE TITLE
Edit comparison page after creating it

### ISSUE THREAD

**Issue by LeonardoB25** [rubynor/bigfive-web#134]
Hello. I think it would be a very useful addition to the compare function to let the user edit a comparison even after creating it, and not only before. 

Right now, it is impossible to do it. So, in order to update even a single person, the user needs to re-insert every name and id of each person each time.

**Comment by maccyber** [comment]
Agreed, good idea. Will add it soon.
Thanks @LeonardoB25

**Comment by maccyber** [comment]
Implemented a button to add additional people to an existing comparison. Need to further consider how to display the edit modal effectively.

![image](https://github.com/rubynor/bigfive-web/assets/701351/d7078b97-6223-44f0-a045-4304eb8d01c5)

**Comment by maccyber** [comment]
Changed it to an 'edit comparison' that redirects back to compare page with ?edit= search param

![image](https://github.com/rubynor/bigfive-web/assets/701351/ba812999-f333-479d-8400-89b0ad9fd8dd)
