### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hoodwhitson** [rubynor/bigfive-web#16]
I love your work transitioning the original Alheimsins Big Five project from Next to Nuxt. It would be great to build upon what you have done. 

The Alheimsins project was under the MIT License:
https://github.com/Alheimsins/bigfive-web/blob/master/LICENSE

Is this project still under the MIT license? Can you clarify if it is still open source?

**Comment by zrrrzzt** [comment]
The project is still open source and under MIT License. We will add the missing files :-)
