### ISSUE TITLE
Environment Variable "MONGODB_URI" references Secret "mongodb_uri", which does not exist.

### ISSUE THREAD

**Issue by lucasrato** [rubynor/bigfive-web#19]
mongodb+srv://user:password@cluster0.zyf9y.azure.mongodb.net/test

So, I'm new to this, but I keep getting this error on vercel. What should I do?

I've ran it on my computer at localhost:3000 fine, without mongodb, but when I try to use vercel, it seems like mongodb is missing. I keep getting this error: **"Environment Variable "MONGODB_URI" references Secret "mongodb_uri", which does not exist."**

What should I do?

**Comment by zrrrzzt** [comment]
Looks like there was a typo in the README. The secrets you'll need to add are MONGODB_URI and MONGODB_COLLECTION.
You can do this from the cli or Vercel's admin page

**Comment by zrrrzzt** [comment]
Sorry, I was too quick here.

Have you added the secret ´mongodb_uri´ to Vercel?

From the cli `vc secrets add mongodb_uri <your-connection-string>` or admin page

**Comment by lucasrato** [comment]
I tried, but I get an error using this command: 

Vercel CLI 20.1.0
Error! The specified scope does not exist
Learn More: https://err.sh/now/scope-not-existent

I've already tried going to this URL and searching it on google. Couldn't find an answer

**Comment by maccyber** [comment]
Try to remove the `scope` setting i `now.json` https://github.com/rubynor/bigfive-web/blob/master/now.json#L3

I'm not sure if that DB-URL will work.

We use something like `mongodb://user:password@host/db`

**Comment by lucasrato** [comment]
@maccyber sorry, I'm completely new to all this... I know user and password because that's pretty straightforward, but I don't know what's my db nor host, couldn't find any of it on mongodb

**Comment by maccyber** [comment]
Seems that you also have to change this: https://github.com/rubynor/bigfive-web/blob/master/nuxt.config.js#L194 to the URL you deployed it to + /api

**Comment by lucasrato** [comment]
Changed and commited to repo. How do I know if it is changed at vercel?
Also, is there a way to test this without going all over the test?

**Comment by maccyber** [comment]
Vercel gives you an unique URL for every deploy, but it should also provide you with an URL for the project (for me it's bigfive-web.rubynor.vercel.app) or you can add your own custom domain. Read the vercel docs for how this is done.
