### ISSUE TITLE
Translate the website to Icelandic

### ISSUE THREAD

**Issue by maccyber** [rubynor/bigfive-web#31]
- Please _know_ the language your translating
- Clone the repo
- Enter the project and run `yarn`
- Go into the folder [translations](https://github.com/rubynor/bigfive-web/tree/master/translations)
- Copy the file of the language you know into a new file
- Use ISO 639-1 language code as file name
- Open the new file and do the translation
- Add the language you translated to [nuxt.config.js](https://github.com/rubynor/bigfive-web/blob/master/nuxt.config.js#L77) under `modules['nuxt-i18n'].locales`
- Run `yarn lint` (or `npm run lint`)  to see that your changes are consistent with the projects coding style
- Run `yarn dev` and open the web-browser at http://localhost:3000
- Change to your translated language in the right dropdown menu and see that the translation looks good.
- Submit the pull request
- Happiness :-)

**Comment by JanitChawla** [comment]
Can i work on this ??

**Comment by Harshalszz** [comment]
Hey! can I work on this.

**Comment by Harshalszz** [comment]
Hey! can you assign this to me.

**Comment by maccyber** [comment]
Sorry for the late reply, sure if you know Icelandic, go ahead :-)
