### ISSUE TITLE
Swedish translation contains a lot of Danish/Norwegian

### ISSUE THREAD

**Issue by tmarkovic** [rubynor/bigfive-web#35]
For example https://github.com/rubynor/bigfive-web/blob/5951c69821771cb0a43df92995fe455ce63d5d0b/translations/sv.js#L9

**Comment by maccyber** [comment]
Thanks for the feedback. Anyone up for grabs?

**Comment by tmarkovic** [comment]
I could take a look at it!

**Comment by sesam** [comment]
See #113 that replaces the Norwegian copypasta with actual Swedish. :)
