### ISSUE TITLE
The dropdown menu is too long

### ISSUE THREAD

**Issue by maccyber** [rubynor/bigfive-web#50]
The dropdown menu is too long, especially for mobile.

We need to find a good solution, so you don't need to scroll down on the menu.

Maybe have an own menu (flag icon with dropdown) for choosing language?

![dropdown-menu](https://user-images.githubusercontent.com/701351/95218076-348cf600-07f4-11eb-8558-e0cc80086500.png)

**Comment by ZenVega** [comment]
hi, i would give it a shot. can u assign this to me?

**Comment by maccyber** [comment]
Sure, done :-)

**Comment by sk6298** [comment]
Hi,I have a solution for this
![Screenshot from 2020-10-06 21-15-12](https://user-images.githubusercontent.com/54492276/95225194-243b4200-0819-11eb-9f35-ca12b656a5bd.png)

**Comment by maccyber** [comment]
@sk6298: You removed the possibility to change the language and the FAQ?

Not really the fix I'm after.

**Comment by sk6298** [comment]
@maccyber : Not removed but they are actually there,You just need to scroll.

**Comment by maccyber** [comment]
Okay, that does not seem very user friendly.

Maybe we can separate the languages in an own menu?
It's still a long list, so we need that menu to support small screens.

**Comment by ZenVega** [comment]
sorry, I'm leaving it to u. I didn't get it was written in vue and I believe I can't find the time to work myself in right now. good luck

**Comment by maccyber** [comment]
Solved by https://github.com/rubynor/bigfive-web/commit/33105be76bd6e2ab86af14946d9466b7f7cf1e04
