### ISSUE TITLE
 Finish translating the file into Spanish

### ISSUE THREAD

**Issue by gareffmz** [rubynor/bigfive-web#56]
I saw that a Spanish translation was added in this Pull Request #49 but it still needs to finish translating (section "opennessToExperience").

Another thing I saw is that not all pages or sections are available for translations, for example.

- Openness to experience 
- Conscientiousness
- Extraversion
- Agreeableness
- Neuroticism
- Privacy, etc.

Only the "Openness_to_experience.vue" uses a translation file, the others don't, I don't know if there is a plan to change this or a reason for that.

If there is no problem, I can finish to translate the es.js file.

**Comment by maccyber** [comment]
Sure, that would be great :-)

Regarding the translation files missing for the other pages, the reason is just pure laziness from my side.
