### ISSUE TITLE
When changing language, menu items does not change language

### ISSUE THREAD

**Issue by maccyber** [rubynor/bigfive-web#64]
Reproduce:
1. Change language on the flag icon
2. Open right menu
3. See that the language is not changed on items, even though they are translated

See the [code](https://github.com/rubynor/bigfive-web/blob/master/components/Toolbar.vue#L94-L101)

This menu should also be an own compoenent.

**Comment by masyoudi** [comment]
@maccyber  do you can check my [https://github.com/rubynor/bigfive-web/pull/66/files](PR)
