### ISSUE TITLE
Cannot change the language of result

### ISSUE THREAD

**Issue by Grix** [rubynor/bigfive-web#7]
Hi, I took the test and chose my local language (Norwegian) without thinking, and thus got my results in Norwegian. But I regretted this because other people wouldn't understand my result if I were to show it to them, and also the translated names of the traits etc makes it harder to google them to get more information.

Therefore I wanted to view my results in English instead. But this does not seem to be possible. When changing to English using the sidebar, my results are still in Norwegian. Some of the page changes, such as the text "Important! Save the following ID to see the results later or compare yourself to others", but the names and explanations of the traits stays Norwegian. This is also the case if I clear my browser cache/cookies. It seems to be tied to the result ID I was given.

To reproduce: Go to https://bigfive-test.com/result/5e7924a30c98860008d2a6b8 , and observe that the results are in Norwegian even if the site language is set to English, at least it is for me.

**Comment by zrrrzzt** [comment]
You are right :-)

@maccyber https://github.com/rubynor/bigfive-web/blob/master/api/result.js#L22 As far as I can see the results is set to data.lang or English and never changed

**Comment by Sebubu** [comment]
Same here. Can't share it with my English peers :(

**Comment by maccyber** [comment]
Donnnnnneeeeee :partying_face:
