### ISSUE TITLE
Save the result ID in localStorage

### ISSUE THREAD

**Issue by maccyber** [rubynor/bigfive-web#71]
Save the result ID in localStorage [here](https://github.com/rubynor/bigfive-web/blob/master/store/index.js#L187).

Display a link to the test result in a notification window at `/result`

**Comment by luvuong-le** [comment]
Hey @maccyber, I can take this one

Got a couple of questions off the top of my head though: 

- I'm assuming we only store one result ID and they be overwritten if a user re-takes the test?
- How do you want the notification window to appear? Underneath the ID input field? or on the top right perhaps?

**Comment by maccyber** [comment]
@luvuong-le: Great, thanks!

I'm sure you will find a good solution for where to position it.
