### ISSUE TITLE
avoid negations

### ISSUE THREAD

**Issue by milahu** [rubynor/bigfive-web#86]
for example:

* Am not bothered by difficult social situations
   * Can easily manage difficult social situations
   * Prefer easy/small social situations
* Am not interested in theoretical discussions
   * Am interested in theoretical discussions
* Have difficulty starting tasks
   * Prefer to start tasks
   * Prefer to start new things (?)
* Try not to think about the needy
   * Prefer to think about the bright sides of life

the question is: should we use binary or ternary logic?
ternary logic uses negations in questions, and a "negation of negation" can be seen as a neutral response,
but here we explicitly provide a "neutral" answer, so i would prefer questions in binary logic

**Comment by maccyber** [comment]
Hey @milahu.

Thanks for the input :-)

The survey are taken from J. A Johnson's https://ipip.ori.org/30FacetNEO-PI-RItems.htm
so if you are looking to change the questionnaire that would be the place to go with your concerns.
