### ISSUE TITLE
Large choice element width can cause accidentally changing a response

### ISSUE THREAD

**Issue by spyoungtech** [rubynor/bigfive-web#94]
Thanks for putting this together. The test was a pretty smooth experience, but wanted to report this one small issue.

While taking the test, I had pulled up other windows over my browser on the left-hand side of my screen. When I clicked on the browser window on the far right-hand side (where no visible elements are located) in order to return to the test in my browser, I happened to notice it changed my response.

I had done this (switching windows) many times while taking it. I wonder now how many times I may have inadvertently changed my responses without noticing.

It seems this is caused by the choice element width extending to most of the page width. 

![image](https://user-images.githubusercontent.com/15212758/138601124-fcc5adba-07b8-4e58-9dc9-3f323f91beba.png)

If possible, I think it would be good if the clickable part of the choice element were restricted to a reasonable area around the visible text/bubble.

**Comment by maccyber** [comment]
Good catch!

Sadly I don't have the time to maintain it at the moment, PRs are welcome ;-)
