### ISSUE TITLE
I want to delete my results

### ISSUE THREAD

**Issue by ShockedCoder** [rubynor/bigfive-web#98]
Personal issues. I do not want them on the website anymore, and I do not think 120$ is a reasonable price to delete my results.

P.S. Realized that the last part of the email was sarcastic and I might have to pay 120$ to delete my results. So I'm reopening this.

**Comment by ShockedCoder** [comment]
I don't want to just publicize the results, so a DM or an email would be much appreciated.

**Comment by mg98** [comment]
https://gdpr-info.eu/art-17-gdpr

**Comment by ShockedCoder** [comment]
Oh right... forgot about that.
I don't remember the link for the survey results anymore and the damage has already been done.
Thanks for your reply, will definitely remember this from now on, if something like this happens again.
